LittleHelpMVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LittleHelpMVC.Data;
using LittleHelpMVC.Models;
using LittleHelpMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LittleHelpMVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly LittleHelpMVCDbContext context;

        public CategoryController(LittleHelpMVCDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<HelpCategory> categories = context.Categories.ToList();
            return View(categories);
        }

        public IActionResult Add()
        {
            AddCategoryViewModel addCategoryViewModel = new AddCategoryViewModel();
            return View(addCategoryViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddCategoryViewModel addCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                HelpCategory helpCategory = new HelpCategory
                {
                    Name = addCategoryViewModel.Name
                };

                context.Categories.Add(helpCategory);
                context.SaveChanges();

                return Redirect("/Category");
            }
            return View(addCategoryViewModel);
        }
    }
}

LittleHelpMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using LittleHelpMVC.Data;
using LittleHelpMVC.Models;
using LittleHelpMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LittleHelpMVC.Controllers
{
    public class UserController : Controller
    {
        private LittleHelpMVCDbContext context;

        public UserController(LittleHelpMVCDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddUserViewModel addUserViewModel = new AddUserViewModel();
            ViewBag.Title = "New Helpers, Register here";
            return View(addUserViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddUserViewModel addUserViewModel)
        {
            //List<User> users = context.Users
            //    .Where(c => (c.Username == addUserViewModel.Username)).ToList();

            User user = context.Users.FirstOrDefault(c => (c.Username == addUserViewModel.Username));

            if (user != null)
            {
                ViewBag.Title = "A Serice Provider already exits with this name !!!";
                return View(addUserViewModel);
            }

            User userEmail = context.Users.FirstOrDefault(c => (c.Email == addUserViewModel.Email));

            if (userEmail != null)
            {
                ViewBag.Title = "A Serice Provider already exists with this email address !!!";
                return View(addUserViewModel);
            }
            if (ModelState.IsValid)
            {
                User newUser = new User
                {
                    Username = addUserViewModel.Username,
                    Screenname = addUserViewModel.Screenname,
                    Email = addUserViewModel.Email,
                    Password = addUserViewModel.Password
                };
                context.Users.Add(newUser);
                context.SaveChanges();

                return RedirectToAction("Add", "LittleHelp",new { name=newUser.Username,scrname=newUser.Screenname});
            }

            return View(addUserViewModel);
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            SignInViewModel signInViewModel = new SignInViewModel();
            ViewBag.Title = "Existing Helpers, Sign In here";
            return View(signInViewModel);

        }

        [HttpPost]
        public IActionResult SignIn(SignInViewModel signInViewModel)
        {
            List<User> users = context.Users.Where(c => (c.Username == signInViewModel.Username)).ToList();

            if (users.Count == 0)
            {
                ViewBag.Title = "No Service Provider, Check the name you entered";
                return View(signInViewModel);
            }
            else
            {
                foreach (var user in users)
                {
                    if (user.Password != signInViewModel.Password)
                    {
                        ViewBag.Title = "Wrong Password";
                        return View(signInViewModel);
                    }

                    if (user.Username != signInViewModel.Username)
                    {
                        ViewBag.Title = "Check the name you entered";
                        return View(signInViewModel);
                    }
                }
            }

            if (ModelState.IsValid)
            {
                List<LittleHelp> helpers = context.Helpers
                         .Where(c => (c.Name == signInViewModel.Username) && (c.ID == signInViewModel.UserId))
                          .Include(c => c.Category).ToList();

                return RedirectToAction("Info", "LittleHelp", new { name = signInViewModel.Username });
            }
            return View(signInViewModel);

        }

        [HttpGet]
        public IActionResult Admin()
        {
            SignInViewModel signInViewModel = new SignInViewModel();
            ViewBag.Title = "Admin, Sign In here";
            return View(signInViewModel);
        }

        [HttpPost]
        public IActionResult Admin(SignInViewModel signInViewModel)
        {
            User user = context.Users.FirstOrDefault(c => c.Username == "Admin");

            if (signInViewModel.Username != "Admin")
            {
                ViewBag.Title = "Check the name you entered";
                return View(signInViewModel);
            }

            if (signInViewModel.Password != "littlehelp")
            {
                ViewBag.Title = "Wrong Password";
                return View(signInViewModel);
            }

            return RedirectToAction("Index", "Admin");
        }
    }
}

LittleHelpMVC/Views/Shared/Welcome.cshtml
<h3>@ViewBag.Title</h3>
<br/>
<a asp-controller="LittleHelp" asp-action="Index">Logout</a>

LittleHelpMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        .center {
            padding: 70px 0;
            text-align: center;
            }

        .dropdown-menu {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
        }

        .dropdown-menu a {
            float: none;
            color: black;
            padding: 10px 10px;
            text-decoration: none;
            display: block;
            text-align: center;
        }

    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse
         navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="LittleHelp" asp-action="Index" class="navbar-brand">LittleHelp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" asp-area="" asp-controller="LittleHelp" asp-action="Index">
                            About<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="LittleHelp" asp-action="About">Why LittleHelp</a></li>
                            <li><a asp-area="" asp-controller="LittleHelp" asp-action="Contact">Contact us</a></li>
                        </ul>
                    </li>

                    @*<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" asp-area="" asp-controller="LittleHelp" asp-action="Add">
                Services<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Electrical</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Handyman</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Heating & A/C</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">HouseCleaning</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Landscaping</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Lawnmower</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Plumbing</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">Snowplower</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">TreeService</a></li>
                <li><a asp-area="" asp-controller="Category" asp-action="Index">FutureUse</a></li>
           </ul>
        </li>*@
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Services</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Index">Service Providers</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Admin">Admin</a></li>

                    @*<li><a asp-area="" asp-controller="LittleHelp" asp-action="Edit">Edit</a> </li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        @*<hr /> *@
        <div class="center">
            <h2>LittleHelp</h2>
            <p>Find your Helper</p>
        </div>
        <footer>
            <p align="right">&copy; 2018 - LittleHelp</p>
        </footer>

    </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)

</body>
</html>